# Generated by Django 2.2.7 on 2019-11-30 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_evaluacion_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_al_curso', to='personas.Curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_de_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_de_los_usario', to='personas.Usuario'),
        ),
    ]
